enum socketRouteList {
  REQUEST_PLAYER_DATA = 'REQUEST_PLAYER_DATA',
  SEND_PLAYER_DATA = 'SEND_PLAYER_DATA',
  SET_PLAYER_NAME = 'SET_PLAYER_NAME',
  SEND_ALL_PLAYERS_DATA = 'SEND_ALL_PLAYERS_DATA',
  // SERVER TO PLAYER
  UPDATE_GAME_DATA = 'UPDATE_GAME_DATA',
  YOUR_TURN = 'YOUR_TURN',
  WAITING_ON_CARD_TARGET = 'WAITING_ON_CARD_TARGET',
  WAITING_ON_PLAYER_TARGET = 'WAITING_ON_PLAYER_TARGET',
  // PLAYER TO SERVER
  PLAY_CARD = 'PLAY_CARD',
  CHOOSE_CARD_TARGET = 'CHOOSE_CARD_TARGET',
  CHOOSE_PLAYER_TARGET = 'CHOOSE_PLAYER_TARGET',
  DISCONNECT_SELF = 'DISCONNECT_SELF',
  UPDATE_GAME_DATA_REFRESH = 'UPDATE_GAME_DATA_REFRESH'
}

export default socketRouteList;
