enum socketRouteList {
  REQUEST_PLAYER_DATA = 'REQUEST_PLAYER_DATA',
  SEND_PLAYER_DATA = 'SEND_PLAYER_DATA',
  SET_PLAYER_NAME = 'SET_PLAYER_NAME',
  SEND_ALL_PLAYERS_DATA = 'SEND_ALL_PLAYERS_DATA'
}

export default socketRouteList;
