enum socketRouteList {
  // SERVER TO PLAYER
  UPDATE_GAME_DATA = 'UPDATE_GAME_DATA',
  YOUR_TURN = 'YOUR_TURN',
  WAITING_ON_CARD_TARGET = 'WAITING_ON_CARD_TARGET',
  WAITING_ON_PLAYER_TARGET = 'WAITING_ON_PLAYER_TARGET',
  SEND_PLAYER_CARD = 'SEND_PLAYER_CARD',
  // PLAYER TO SERVER
  SET_PLAYER_NAME = 'SET_PLAYER_NAME',
  PLAY_CARD = 'PLAY_CARD',
  CHOOSE_CARD_TARGET = 'CHOOSE_CARD_TARGET',
  CHOOSE_PLAYER_TARGET = 'CHOOSE_PLAYER_TARGET',
  DISCONNECT_SELF = 'DISCONNECT_SELF',
  UPDATE_GAME_DATA_REFRESH = 'UPDATE_GAME_DATA_REFRESH'
}

export default socketRouteList;
